name: Load Test
on: [push]
jobs:
  build: 
    name: K6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v4
      - name: Step 2 - Runs Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: scripts/conteudo-adicional-aws.js
